---
galaxy_info:
  role_name: collect_diagnostics
  namespace: jumpstarter
  author: Alex Benavides <abenavid@redhat.com>
  description: Collects Jumpstarter diagnostics from an Ansible execution environment.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
